// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertImageToBase64(arg1) {
  return window['go']['main']['App']['ConvertImageToBase64'](arg1);
}

export function GetImageMD5(arg1) {
  return window['go']['main']['App']['GetImageMD5'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenImageDialog(arg1) {
  return window['go']['main']['App']['OpenImageDialog'](arg1);
}

export function UrlToBase64(arg1) {
  return window['go']['main']['App']['UrlToBase64'](arg1);
}
