// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConvertImageToBase64(arg1:string):Promise<main.ImageInfo>;

export function GetImageMD5(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function OpenImageDialog(arg1:string):Promise<main.ImageDialogResult>;

export function UrlToBase64(arg1:string):Promise<string>;
